# Build
FROM node:12.16.3-alpine as build

WORKDIR /app

COPY package.json yarn.lock /app/

RUN yarn install

COPY . /app/

RUN yarn build

# production environment
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

# start nginx
CMD ["nginx", "-g", "daemon off;"]