version: '3'
 
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
    ports:
      - ${PORT}:${PORT}
    command: yarn start